app = "todo-app-sample"
primary_region = "nrt"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
processes = ["app"]

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1
